Laundry.Web/Areas/Admin/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laundry.BLL;
using Microsoft.Reporting.WebForms;
using System.Data;
using Laundry.Web.ReportDataset;

namespace Laundry.Web.Areas.Admin.Controllers
{
    public class ReportController : Controller
    {
        ReportBs NewReportBs = new ReportBs();
        HashHelper helper = new HashHelper();
        CompanyDetailBs NewCompanyDetailBs = new CompanyDetailBs();
        // GET: Admin/Report
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        //public ActionResult SalesReport()
        //{
        //    try
        //    {
        //        ViewBag.UserId = Session["Username"].ToString();
        //    }
        //    catch
        //    {
        //        Session["ConfirmLogin"] = "You must login first";
        //        return RedirectToAction("Login", new { Area = "Security", Controller = "Access" });
        //    }
        //    return View();
        //}
        public ActionResult SalesReport(string txtStartDate = "01/01/1900", string txtEndDate = "01/01/1900", string PageNo = null)
        {
            try
            {
                ViewBag.UserId = Session["Username"].ToString();
            }
            catch
            {
                Session["ConfirmLogin"] = "You must login first";
                return RedirectToAction("Login", new { Area = "Security", Controller = "Access" });
            }
            DateTime StartDate = DateTime.Today;
            DateTime EndDate = DateTime.Today;
            int pageNo = int.Parse(PageNo == null ? "1" : PageNo);
            ViewBag.CurrentPage = pageNo;
            ViewBag.StartDate = txtStartDate;
            ViewBag.EndDate = txtEndDate;
            Session["StartDate"] = StartDate = Convert.ToDateTime(txtStartDate);
            Session["EndDate"] = EndDate = Convert.ToDateTime(txtEndDate);
            ViewBag.TotalPages = NewReportBs.SalesReportPages(StartDate, EndDate);
            return View(NewReportBs.SalesReport(StartDate, EndDate).Skip((pageNo - 1) * 10).Take(10));
        }
        //[HttpPost]
        //public ActionResult SalesReport(FormCollection frm)
        //{
        //    DateTime StartDate = DateTime.Today;
        //    DateTime EndDate = DateTime.Today;
        //    //Session["StartDate"] = StartDate = Convert.ToDateTime(frm["txtStartDate"]);
        //    // Session["EndDate"] =EndDate = Convert.ToDateTime(frm["txtEndDate"]);

        //    //Session["StartDate"] = StartDate = Convert.ToDateTime(helper.ValidateDate(frm["txtStartDate"]));
        //    //Session["EndDate"] = EndDate = Convert.ToDateTime(helper.ValidateDate(frm["txtEndDate"]));

        //    Session["StartDate"] = StartDate = Convert.ToDateTime(frm["txtStartDate"]);
        //    Session["EndDate"] = EndDate = Convert.ToDateTime(frm["txtEndDate"]);
        //    return View(NewReportBs.SalesReport(StartDate, EndDate));
        //}

       
        public FileResult ExportSalesReport(string ReportType = "Pdf")
        {
            LocalReport localReport = new LocalReport();
            localReport.SubreportProcessing += new SubreportProcessingEventHandler(LocalReport_SubreportProcessing);
            localReport.ReportPath = Server.MapPath("~/Reports/SalesReportNew.rdlc");
            ReportDataSource reportDtSource = new ReportDataSource();

            DataRow dr;
            ReportDataSet ds = new ReportDataSet();

            foreach (var sale in NewReportBs.SalesReport(Convert.ToDateTime(Session["StartDate"]), Convert.ToDateTime(Session["EndDate"])))
            {
                dr = ds.Tables["SalesReportDT"].Rows.Add();
                dr["AmountPaid"] = sale.AmountPaid;
                dr["CustomerName"] = sale.Customer.Surname;
                dr["CustomerTag"] = sale.CustomerTag;
                dr["KeyDate"] = sale.KeyDate;
                dr["PaymentNo"] = sale.PaymentNo;
                dr["StartDate"] = Session["StartDate"];
                dr["EndDate"] = Session["EndDate"];
            }

            //reportDtSource.Name = "SalesReportDataSet";
            //reportDtSource.Value = NewReportBs.SalesReport(Convert.ToDateTime(Session["StartDate"]), Convert.ToDateTime(Session["EndDate"]));
            reportDtSource.Name = "ReportDataSet";
            reportDtSource.Value= ds.Tables["SalesReportDT"];

            localReport.DataSources.Add(reportDtSource);
            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension = (ReportType == "Excel") ? "xlsx" : "pdf";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;
            renderedBytes = localReport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension,
                                            out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment; filename=SalesReport " + DateTime.Now + "." + fileNameExtension);
            return File(renderedBytes, fileNameExtension);
        }

        void LocalReport_SubreportProcessing(object sender, SubreportProcessingEventArgs e)
        {
            LocalReport localReport = new LocalReport();
            e.DataSources.Add(new ReportDataSource()
            {
                Name = "CompDetDataSet",
                Value = NewCompanyDetailBs.GetCompanyDetailList()
            });
        }
    }
}

Laundry.Web/Areas/User/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laundry.BLL;
using Microsoft.Reporting.WebForms;
using System.Data;
using Laundry.Web.ReportDataset;
namespace Laundry.Web.Areas.User.Controllers
{
    public class ReportController : Controller
    {
        ReportBs NewReportBs = new ReportBs();
        HashHelper helper = new HashHelper();
        CompanyDetailBs NewCompanyDetailBs = new CompanyDetailBs();
        // GET: User/Report
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        // public ActionResult SalesReport)
        public ActionResult SalesReport(string txtStartDate = "01/01/1900", string txtEndDate = "01/01/1900", string PageNo = null)
        {
            try
            {
                ViewBag.UserId = Session["Username"].ToString();
            }
            catch
            {
                Session["ConfirmLogin"] = "You must login first";
                return RedirectToAction("Login", new { Area = "Security", Controller = "Access" });
            }
            DateTime StartDate = DateTime.Today;
            DateTime EndDate = DateTime.Today;
            int pageNo = int.Parse(PageNo == null ? "1" : PageNo);
            ViewBag.CurrentPage = pageNo;
            ViewBag.StartDate = txtStartDate;
            ViewBag.EndDate = txtEndDate;
            if (Convert.ToDateTime(txtStartDate) > Convert.ToDateTime(txtEndDate))
            {
                ViewBag.Message = "StartDate must not be greater than end date";
                return View();
            }
            Session["StartDate"] = StartDate = Convert.ToDateTime(txtStartDate);
            Session["EndDate"] = EndDate = Convert.ToDateTime(txtEndDate);
            ViewBag.TotalPages = NewReportBs.SalesReportPages(StartDate, EndDate);
            var result = NewReportBs.SalesReport(StartDate, EndDate).Skip((pageNo - 1) * 10).Take(10);

            if (Session["Role"].ToString().ToLower() != "administrator")
                result = result.Where(c => c.BranchID == Convert.ToInt32(Session["BranchID"]));
                return View(result);
        }

        [HttpGet]
        public ActionResult SalesReportPaging(string str_date, string end_date, string PageNo)
        {
            return RedirectToAction("SalesReport", new { txtStartDate = str_date, txtEndDate = end_date, PageNo = PageNo });
        }


        public FileResult ExportSalesReport(string ReportType = "Pdf")
        {
            LocalReport localReport = new LocalReport();
            localReport.SubreportProcessing += new SubreportProcessingEventHandler(LocalReport_SubreportProcessing);
            //localReport.ReportPath = Server.MapPath("~/Reports/SalesReport.rdlc");
            localReport.ReportPath = Server.MapPath("~/Reports/SalesReportNew.rdlc");
            ReportDataSource reportDtSource = new ReportDataSource();
            DataRow dr;
            ReportDataSet ds = new ReportDataSet();
            var result = NewReportBs.SalesReport(Convert.ToDateTime(Session["StartDate"]), Convert.ToDateTime(Session["EndDate"]));
            if (Session["Role"].ToString().ToLower() != "administrator")
                result = result.Where(c => c.BranchID == Convert.ToInt32(Session["BranchID"]));
                foreach (var sale in result)
            {
                dr = ds.Tables["SalesReportDT"].Rows.Add();
                dr["AmountPaid"] = sale.AmountPaid;
                dr["CustomerName"] = sale.Customer.Surname.ToString() + ' ' + sale.Customer.Othername.ToString();
                dr["CustomerTag"] = sale.CustomerTag;
                dr["KeyDate"] = sale.KeyDate;
                dr["PaymentNo"] = sale.PaymentNo;
                dr["StartDate"] = Session["StartDate"];
                dr["EndDate"] = Session["EndDate"];
            }

            //reportDtSource.Name = "SalesReportDataSet";
            //reportDtSource.Value = NewReportBs.SalesReport(Convert.ToDateTime(Session["StartDate"]), Convert.ToDateTime(Session["EndDate"]));
            reportDtSource.Name = "ReportDataSet";
            reportDtSource.Value = ds.Tables["SalesReportDT"];
            localReport.DataSources.Add(reportDtSource);
            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension = (ReportType == "Excel") ? "xlsx" : "pdf";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;
            renderedBytes = localReport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension,
                                            out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment; filename=SalesReport " + DateTime.Now + "." + fileNameExtension);
            return File(renderedBytes, fileNameExtension);
        }

        void LocalReport_SubreportProcessing(object sender, SubreportProcessingEventArgs e)
        {
            LocalReport localReport = new LocalReport();
            e.DataSources.Add(new ReportDataSource()
            {
                Name = "CompDetDataSet",
                Value = NewCompanyDetailBs.GetCompanyDetailList()
            });
        }
    }
}

Laundry.Web/Areas/Admin/Views/Report/SalesReport.cshtml
@model IEnumerable<Laundry.Model.PaymentDetail>

@{
    ViewBag.Title = "SalesReport";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}

<h2>Sales Report</h2>
@using (Html.BeginForm("SalesReport", "Report", FormMethod.Get, new { PageNo = "1", Area="Admin"}))
{
    @*@Html.AntiForgeryToken()*@

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="txtStartDate" id="txtStartDate" class="form-control" value="@ViewBag.StartDate" />
                @Html.ValidationMessage("", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("End Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="txtEndDate" id="txtEndDate" class="form-control" value="@ViewBag.EndDate" />
                @Html.ValidationMessage("", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Print" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div class="container">
        @Html.ActionLink("Excel", "ExportSalesReport", new { ReportType = "Excel" })
        @Html.ActionLink("PDF", "ExportSalesReport", new { ReportType = "pdf" })
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead style="color:blueviolet;">
                    <tr>
                        <th>
                            @*@Html.DisplayNameFor(model => model.KeyDate)*@
                            Transaction Date
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PaymentNo)
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(model => model.CustomerName)*@
                            Customer Name
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CustomerTag)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AmountPaid)
                        </th>
                    </tr>
                </thead>

                @if (Model != null)
                {

                    double TotalCost = 0.00;
                    foreach (var item in Model)
                    {
                        TotalCost = TotalCost + item.AmountPaid;

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.KeyDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Customer.Surname)  @Html.DisplayFor(modelItem => item.Customer.Othername)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CustomerTag)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AmountPaid)
                            </td>
                        </tr>
                    }
                    <tfoot style="color:blueviolet;">
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><b>Total Sales</b></td>
                            <td>
                                <b>@TotalCost</b>
                            </td>
                        </tr>
                    </tfoot>
                }

            </table>
        </div>
    </div>
    if (ViewBag.TotalPages != null)
    {
        double TotalPages = ViewBag.TotalPages;
        <ul class="pagination">
            @for (int i = 1; i <= TotalPages; i++)
            {
                <li class="pageno">@*@Html.ActionLink(@i.ToString(), "SalesReportPaging", new {Area="User", Controller="Report",  str_date= ViewBag.StartDate,  end_date= ViewBag.EndDate, PageNo = i })*@</li>
                <li class="pageno">@Html.ActionLink(@i.ToString(), "SalesReport", new { Area = "Admin", Controller = "Report", txtStartDate = ViewBag.StartDate, txtEndDate = ViewBag.EndDate, PageNo = i })</li>
                @*<li class="pageno">@Html.ActionLink(@i.ToString(), "", new { Area = "", Controller = "", PageNo = i })</li>*@
            }

        </ul>

    }

}