Laundry.Web/Areas/Customer/Controllers/SearchController.cs
using Laundry.BLL;
using Laundry.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laundry.Web.Areas.Customer.Controllers
{
    public class SearchController : Controller
    {
        // GET: Customer/Search
        CustomerBs NewCustomerBs = new CustomerBs();
        Model.Customer CustomerObj = new Model.Customer();
        public ActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        //public ActionResult Search()
        //{
        //    try
        //    {
        //        ViewBag.UserId = Session["Username"].ToString();
        //    }
        //    catch
        //    {
        //        Session["ConfirmLogin"] = "You must login first";
        //        return RedirectToAction("Login", new { Area = "Security", Controller = "Access" });
        //    }
        //    return View();
        //}

        //// [ValidateAntiForgeryToken]
        //[HttpPost]
        //public ActionResult Search(string type, string value, string startdate, string enddate)
        //{


        //    DateTime FinalStartDate = DateTime.Today, FinalEndDate = DateTime.Today;
        //    if (startdate != "" && DateTime.TryParse(startdate, out FinalStartDate))
        //    {
        //        //FinalStartDate = Convert.ToDateTime(ConvertToDateFormat(startdate));
        //        FinalStartDate = Convert.ToDateTime(startdate);
        //    }

        //    if (enddate != "" && DateTime.TryParse(enddate, out FinalEndDate))
        //    {
        //        FinalEndDate = Convert.ToDateTime(enddate);
        //    }

        //    return View(NewTransactionBs.Search(type, value, FinalStartDate, FinalEndDate));
        //}

        //[HttpGet]
        //public ActionResult _CustomerSearch()
        //{
        //    try
        //    {
        //        ViewBag.UserId = Session["Username"].ToString();
        //    }
        //    catch
        //    {
        //        Session["ConfirmLogin"] = "You must login first";
        //        return RedirectToAction("Login", new { Area = "Security", Controller = "Access" });
        //    }
        //    return PartialView();
        //}

        //[ValidateAntiForgeryToken]
        //[HttpPost]
        //public ActionResult _AddItem(FormCollection collection)
        //{
        //    var Clothes = NewClothingBS.ListAll();
        //    ViewBag.Code_Desc = new SelectList(Clothes, "ClothId", "ClothDesc");
        //    ViewBag.Color = new SelectList(NewCodesBs.GetByCodeType("Cod001"), "Codes_Val", "Codes_Desc");
        //    ViewBag.CollectionType = new SelectList(NewCodesBs.GetByCodeType("Cod002"), "Codes_Val", "Codes_Desc");
        //    ViewBag.StarchLevel = new SelectList(NewCodesBs.GetByCodeType("Cod003"), "Codes_Val", "Codes_Desc");
        //    ViewBag.PressingOption = new SelectList(NewCodesBs.GetByCodeType("Cod004"), "Codes_Val", "Codes_Desc");

        //    return PartialView();
        //}

        public JsonResult GetCustomerByPhoneNumber(string phone)
        {
            var result = NewCustomerBs.GetByPhoneNumber(phone);
            Model.Customer MyResult = new Model.Customer();

            if (result != null)
            {
                MyResult.Surname = result.Surname;
                MyResult.Othername = result.Othername;
                MyResult.EmailAddress = result.EmailAddress;
                MyResult.Sex = result.Sex;
                MyResult.Address = result.Address;
                MyResult.CustomerId = result.CustomerId;
            }
            return Json(MyResult, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCustomerByEmail(string email)
        {
            var result = NewCustomerBs.GetByEmail(email);
            Model.Customer MyResult = new Model.Customer();

            if (result != null)
            {
                MyResult.Surname = result.Surname;
                MyResult.Othername = result.Othername;
                MyResult.CustomerPhone = result.CustomerPhone;
            }
            return Json(MyResult, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CustomerSearch(string name, string PageNo = null)
        {
            try
            {
                ViewBag.UserId = Session["Username"].ToString();
            }
            catch
            {
                Session["ConfirmLogin"] = "You must login first";
                return RedirectToAction("Login", new { Area = "Security", Controller = "Access" });
            }

            int pageNo = int.Parse(PageNo == null ? "1" : PageNo);
            ViewBag.CurrentPage = pageNo;
            ViewBag.name = name;

            Session["NameSearch"] = name;
            var CustomerSearchResult = NewCustomerBs.SearchCustomerByName(name);
            ViewBag.TotalPages = NewCustomerBs.CustomerSearchTotalPages(CustomerSearchResult.Count());
            return View(CustomerSearchResult.Skip((pageNo - 1) * 10).Take(10));
        }

        public ActionResult Overview(string phonenumber)
        {
            try
            {
                ViewBag.UserId = Session["Username"].ToString();
            }
            catch
            {
                Session["ConfirmLogin"] = "You must login first";
                return RedirectToAction("Login", new { Area = "Security", Controller = "Access" });
            }
            return View(NewCustomerBs.GetByPhoneNumber(phonenumber));
        }
    }
}

Laundry.Web/Areas/Customer/Views/Search/CustomerSearch.cshtml
@model IEnumerable<Laundry.Model.Customer>

@{
    ViewBag.Title = "CustomerSearch";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}

<h2>Customer Search</h2>
@using (Html.BeginForm("CustomerSearch", "Search", FormMethod.Get, new { PageNo = "1", Area = "Customer" }))
{
    @*@Html.AntiForgeryToken()*@
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container text-capitalize" style="margin-bottom:2px; font-size:14px;">
            @if (ViewBag.Message != null && ViewBag.Message.ToString() != "")
            {
                <div class="bg-danger alert alert-dismissable" style="margin-top:1px;">
                    @ViewBag.Message
                </div>
            }
        </div>

        <div class="form-group">
            @Html.Label("Name or Phone Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    <input type="text" name="name" id="name" class="form-control" value="@ViewBag.name" required="required" />
                    @Html.ValidationMessage("", "", new { @class = "text-danger" })
                </div>
        </div>

        <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-primary" />
        </div>
    </div>
    </div>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead style="color:blueviolet;">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Surname)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Othername)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Sex)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CustomerPhone)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.EmailAddress)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.Reg_Status)
                        </th>*@
                        @*<th></th>*@
                    </tr>
                </thead>
                @if (Model != null)
                {

                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                          @Html.ActionLink(item.Surname, "Overview", new { Controller = "Search", Area = "Customer", phonenumber=item.CustomerPhone})
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Othername)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sex)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CustomerPhone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmailAddress)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Reg_Status)
                            </td>*@
                            @*<td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.CustomerId }) |
                                @Html.ActionLink("Details", "Details", new { id = item.CustomerId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.CustomerId })
                            </td>*@
                        </tr>
                    }
                }

            </table>
        </div>
    </div>
}

Laundry.Web/Areas/Customer/Views/Search/Overview.cshtml
@model Laundry.Model.Customer

@{
    ViewBag.Title = "Overview";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
    <link href="~/Content/simple-sidebar.css" rel="stylesheet" />
    Session["CustomerName"] = Model.Surname + " " + Model.Othername;
}

<h2>Customer Overview</h2>

<div>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="section panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title">Customer Information</h3></div>
                    <div class="panel-body">
                        <fieldset class="form-horizontal">
                            <div class="form-group">
                                <label class="col-md-4">Surname:</label><div class="col-md-8"><span>@Model.Surname</span></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4">Othername:</label><div class="col-md-8"><span>@Model.Othername</span></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4">Sex:</label><div class="col-md-8"><span>@Model.Sex</span></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4">Phone Number:</label><div class="col-md-8"><span>@Model.CustomerPhone</span></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4">Email Address:</label><div class="col-md-8"><span>@Model.EmailAddress</span></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4">Address:</label><div class="col-md-8"><span>@Model.Address</span></div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-menu">
                    <div class="panel-heading">
                        <h4 class="panel-title">Related Items</h4>
                    </div>
                    <div class="panel-body page-menu">
                        <ul>
                            <li class="selected">@Html.ActionLink("Update Customer", "UpdateCustomer", new { Controller = "Registration", Area = "Security", phonenumber = @Model.CustomerPhone })</li>
                            <li>@Html.ActionLink("Transaction Entry", "TransEntry", new { Controller = "Transaction", Area = "User", phonenumber = @Model.CustomerPhone })</li>
                            <li>@Html.ActionLink("Recent Transactions", "TransactionHistory", new { Controller = "Transaction", Area = "User", phonenumber = @Model.CustomerPhone })</li>
                        </ul>
                    </div>


                </div>


            </div>
        </div>
    </div>
</div>

Laundry.Web/Areas/Customer/Views/Search/_CustomerSearch.cshtml
@using (Html.BeginForm())
{
    <div class="container">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <td>
                            <label>Search By</label>
                        </td>
                        <td class="others-toggle turn-off-display">
                            <label id="DisplaySearchName" name="DisplaySearchName">Value</label>
                        </td>
                        <td class="date-toggle turn-off-display">
                            <label> Start Date</label>
                        </td>
                        <td class="date-toggle turn-off-display">
                            <label>End Date</label>
                        </td>
                        <td></td>
                    </tr>
                </thead>
                <tr>
                    <th>
                        <select name="type" id="type" class="form-control">
                            <option value="Select" selected>Select</option>
                            <option value="TransNo">Transaction Number</option>
                            <option value="Name">Email Address</option>
                        </select>
                    </th>
                    <th class="others-toggle turn-off-display">
                        <input type="text" name="value" id="value" class="form-control" />
                    </th>
                    <th class="date-toggle turn-off-display">
                        <input type="date" name="startdate" id="startdate" class="form-control" />
                    </th>
                    <th class="date-toggle turn-off-display">
                        <input type="date" name="enddate" id="enddate" class="form-control" />
                    </th>
                    <th>
                        <input type="submit" value="Search" class="btn btn-default" />
                    </th>
                </tr>
                @*<tr><td colspan="4"><input type="submit" value="Search" class="btn btn-default" /></td></tr>*@


            </table>
        </div>
    </div>
}